### ISSUE TITLE
Bonus task #1

### ISSUE THREAD

**Issue by novachok** [OlgaKlekot/PhpLab#1]
https://github.com/OlgaKlekot/PhpLab/blob/master/task1/bonus.php#L5
в цілому задача вирішена, але!!
кондішен: $str == !ctype_alpha($str) - не правильний по суті,
подумай і скажи чому.

**Comment by OlgaKlekot** [comment]
тому що ctype_alpha робить перевірку, і прирівнювати до нього $str - безглуздо))

**Comment by novachok** [comment]
так, молодець ;)
тому що тут достатньо одного ctype - він поверне TRUE || FALSE - і цього достатньо
а стрінг при приведені типів, якщо вона не пуста - це TRUE
і получается ти порівнюєш результат перевірки до ТРУ

**Comment by OlgaKlekot** [comment]
вже виправила)
