### ISSUE TITLE
#3

### ISSUE THREAD

**Issue by novachok** [OlgaKlekot/PhpLab#2]
https://github.com/OlgaKlekot/PhpLab/blob/master/task3_Arrays/index.php#L5
робота з масивом через "рядок" - не дуже доцільно, це можна було б зробити через array_fill

https://github.com/OlgaKlekot/PhpLab/blob/master/task3_Arrays/index.php#L31
трошки за-складно вибираэш середину - можна на багато простіше, але відповідь приймається

https://github.com/OlgaKlekot/PhpLab/blob/master/task3_Arrays/index.php#L138
чому форіч? чому не array_map ?

**Comment by OlgaKlekot** [comment]
https://github.com/OlgaKlekot/PhpLab/blob/master/task3_Arrays/index.php#L5
змінила на array_fill

https://github.com/OlgaKlekot/PhpLab/blob/master/task3_Arrays/index.php#L138
змінила на  array_map, хоч форіч здавався мені нескладнішим

https://github.com/OlgaKlekot/PhpLab/blob/master/task3_Arrays/index.php#L31
так - доволі заплутано, проте мені подобається, але якщо треба, то я поміняю

**Comment by OlgaKlekot** [comment]
а що треба виправити в https://github.com/OlgaKlekot/PhpLab/tree/master/task2 ??
